.TH YMPBYC 1

.SH NAME

ympbyc - programmer
.SH SYNOPSIS

.I ympbyc [options...] text

.SH DESCRIPTION

18 yrsold programmer working part time in Ebisu Tokyo. Graduated a college in New Zealand in 2011 

.PP
 _

.SH SEE ALSO

twitter: http://twitter.com/ympbyc 
.PP

 blog : http://d.hatena.ne.jp/ympbyc 
.PP

 Make::Booth : http://makebooth.com/booth/ympbyc 
.PP

 gist : http://gist.github.com/ympbyc
